services:
  # Serviço do Banco de Dados
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: crm_db
      POSTGRES_USER: usuario_crm
      POSTGRES_PASSWORD: senha_forte_123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Serviço da API Java
  api:
    build: .
    container_name: spring_api
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      # O host da URL é o nome do serviço 'db' definido acima
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/crm_db
      SPRING_DATASOURCE_USERNAME: usuario_crm
      SPRING_DATASOURCE_PASSWORD: senha_forte_123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"

volumes:
  postgres_data: